version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.3.8.21-alpine
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9363:9363"
      - "9100:9100"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - /mnt/data:/mnt/data
      - ./.config/config.d/disks.xml:/etc/clickhouse-server/config.d/disks.xml:ro
      - ./.config/config.d/listen.xml:/etc/clickhouse-server/config.d/listen.xml:ro
      - ./.config/users.d/default-password.xml:/etc/clickhouse-server/users.d/default-password.xml:ro
      - ./.config/users.d/drop_limits.xml:/etc/clickhouse-server/users.d/drop_limits.xml:ro
      - ./.config/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml:ro
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - coolify

volumes:
  clickhouse_data:


networks:
  coolify:
    external: true
